### ISSUE TITLE
Type 'N' cannot be used to index type 'NumberToString' with TS 2.5.2 when importing Ramda

### ISSUE THREAD

**Issue by alshain** [types/npm-ramda#234]
According to the manual, I've installed the typings with `npm install --save-dev types/npm-ramda#dist`

```ts
import * as R from 'ramda';
```

leads to the following error:

> node_modules\@types\ramda\src\view.d.ts
`(90,12): error TS2536: Type 'N' cannot be used to index type 'NumberToString'.`

packge.json excerpt:

```javascript

"@types/ramda": "github:types/npm-ramda#dist",
"ramda": "^0.24.1",
"typescript": "^2.5.2"
```

**Comment by alshain** [comment]
Using `"@types/ramda": "^0.24.9"` instead, as generated by a regular `npm install -S @types/ramda` works fine with said code and TS 2.5.2

**Comment by tycho01** [comment]
Sounds like https://github.com/Microsoft/TypeScript/issues/15768, which I imagine should have made it in. Bit surprised, think @ikatyang had tried with `2.5.2` at https://github.com/types/npm-ramda/pull/224.

**Comment by ikatyang** [comment]
I'm not sure why the error did not occur in the build, but I already have a fix for it in #233 though it'll cause TS 2.4 to error since the bug fix was in TS 2.5.

I'll port them to master later.

**Comment by ikatyang** [comment]
@alshain 

The definition from `npm install -S @types/ramda` is currently maintained by DefinitelyTyped, and we're [trying to generate DT compatible definitions so as to put them on DT](https://github.com/types/npm-ramda/issues/191).

**Comment by alshain** [comment]
@ikatyang Thanks for the link, I was wondering why Ramda linked here rather than to DefinitelyTyped.

**Comment by tycho01** [comment]
@alshain: it's because the definitions over there aren't actively maintained (not to mention it's tougher to discuss issues without a distinct repo); it's been the intention to sync the types here back to there, but it hadn't happened yet so far.

**Comment by jiayihu** [comment]
I'm having the same issue, is there any workaround available for the moment?

**Comment by ikatyang** [comment]
@jiayihu 

It should be fixed in TS v2.5+, if you're talking about prior to v2.5, you have to add `skipLibCheck: true` to your `tsconfig.json`.

**Comment by jiayihu** [comment]
Thanks for the reply, I confirm it has been solved by updating TS to `2.5.3`!

**Comment by bstro** [comment]
I'm on typescript `2.5.3` using `"@types/ramda": "types/npm-ramda#dist"` and I get the following error:

```/Users/bstro/foo/node_modules/@types/ramda/src/view.d.ts
(89,10): error TS2536: Type 'N' cannot be used to index type 'U'.```

**Comment by ikatyang** [comment]
@bstro 

It shouldn't get errors with default config. Can you share some steps to reproduce? I'm not able to reproduce the issue, here's how I tested:

```sh
mkdir ramda-test
cd ramda-test
yarn add types/npm-ramda#dist typescript --force
echo '{"compilerOptions": {"strict": true}}' > tsconfig.json
echo 'import * as R from "ramda"; R.view(R.lensIndex(0), [0, 1, 2]);' > test.ts
yarn tsc -p tsconfig.json
```
